blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('' , views.PostView.as_view(), name='home'),
    path('details/<slug:slug>' , views.DetailView.as_view() , name='details'),
    path('like/<slug:slug>/<int:pk>' , views.like , name='like'),
]

tiphub_test/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('blog.urls'))
]+ static(settings.MEDIA_URL , document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    conttent = models.TextField()
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog' , null=True , blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post , self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:details' , kwargs={'slug':self.slug})
        
class Like(models.Model):
    users = models.ForeignKey(User, related_name='likes' , on_delete=models.CASCADE)
    posts = models.ForeignKey(Post, related_name='likes' , on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.users.email} - {self.posts.title}"

        

blog/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import  ListView , DetailView
from .models import Like, Post

class PostView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'

class DetailView(DetailView):
    model = Post
    template_name = 'blog/details.html'
    context_object_name = 'posts'
    def get_context_data(self , *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated == True:
            if self.request.user.likes.filter(posts__title = self.object.title , users_id = self.request.user.id).exists():
                context['is_liked'] = True
            else:
                context['is_liked'] = False
        else:
            pass
        return context 

def like(request , slug , pk):
    try:
        like = Like.objects.get(posts__slug = slug , users_id=request.user.id)
        like.delete()
        # return JsonResponse({"response" : "unliked"})
    except:
        Like.objects.create(posts_id=pk , users_id = request.user.id)
        # return JsonResponse({"response" : "liked"})
    return redirect('blog:details' , slug)

blog/templates/blog/details.html
{% load static %}
{% load social_share %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static "js/jquery.min.js" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://kit.fontawesome.com/1cd78581a0.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{posts.title}}</title>
</head>
<body>
    <article>
        <h2>{{posts.title}}</h2>
        <div>{{posts.author}}</div>
        <div>{{posts.created}}</div>
        <p>{{posts.conttent}}</p>
        {% if request.user.is_authenticated == True %}
        <div>  
            {% if is_liked %}
            <a href="{% url 'blog:like' posts.slug posts.id %}"><i id="like" style="color:red" class="fa-solid fa-heart"><span id="count">{{posts.likes.count}}</span></i></a>                                   
            {% else %}
            <a href="{% url 'blog:like' posts.slug posts.id %}"><i id="like" style="color:red" class="fa-regular fa-heart"><span id="count">{{posts.likes.count}}</span></i></a></a>
            {% endif %}
        </div>
        {% endif %}
    </article>
    <div class="share">
        <span>{% post_to_whatsapp posts.get_absolute_url  'Whatsapp' %}</span>
        <span class="post-share">{% post_to_telegram 'plese see the new post in the site' posts.get_absolute_url 'telegram' %}</span>
        <span class="post-share">{% send_email 'plese see the new post in the site'  posts.get_absolute_url  'email' %}</span>
    </div>
</body>
</html>

blog/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
    <title>tiphub.net</title>
</head>
<body>
    <h1>Welcome Tiphub</h1>
    <hr>
    <ul>
        {% for post in posts %}
        <article>
            <a href="details/{{post.slug}}"><h2>{{post.title}}</h2></a>
            <div>{{post.author}}</div>
            <div>{{post.created}}</div>
            <p>{{post.conttent}}</p>
        </article>
        <hr>
        {% endfor %}
    </ul>
</body>
</html>